//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoAtos {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsApp : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsApp defaultInstance = ((SettingsApp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsApp())));
        
        public static SettingsApp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:proyectosbasesayungan.database.windows.net,1433;Initial Catalog=rioeve" +
            "ntosdb;Persist Security Info=False;User ID=ayungan;Password=Cuka2205;MultipleAct" +
            "iveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout" +
            "=30;")]
        public string cadena_conexion {
            get {
                return ((string)(this["cadena_conexion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pro_verificarUsuario")]
        public string p_veriicarUsuario {
            get {
                return ((string)(this["p_veriicarUsuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pro_usuario_insertar")]
        public string pro_usuario_insertar {
            get {
                return ((string)(this["pro_usuario_insertar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pro_listar_Usuario")]
        public string pro_listar_Usuario {
            get {
                return ((string)(this["pro_listar_Usuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pro_eliminar_usuario")]
        public string pro_eliminar_usuario {
            get {
                return ((string)(this["pro_eliminar_usuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_mostrar_dispositivo")]
        public string p_mostrar_dispositivo {
            get {
                return ((string)(this["p_mostrar_dispositivo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_mostrar_dispositivo_id")]
        public string p_mostrar_dispositivo_id {
            get {
                return ((string)(this["p_mostrar_dispositivo_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_mostrar_asignacion")]
        public string p_mostrar_asignacion {
            get {
                return ((string)(this["p_mostrar_asignacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_mostrar_asignacion_id")]
        public string p_mostrar_asignacion_id {
            get {
                return ((string)(this["p_mostrar_asignacion_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_insertar_dispositivo")]
        public string p_insertar_dispositivo {
            get {
                return ((string)(this["p_insertar_dispositivo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_update_dispositivo")]
        public string p_update_dispositivo {
            get {
                return ((string)(this["p_update_dispositivo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_delete_dispositivo")]
        public string p_delete_dispositivo {
            get {
                return ((string)(this["p_delete_dispositivo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_mostrar_asignacion_id_usuario")]
        public string p_mostrar_asignacion_id_usuario {
            get {
                return ((string)(this["p_mostrar_asignacion_id_usuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pro_usuario_update")]
        public string pro_usuario_update {
            get {
                return ((string)(this["pro_usuario_update"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_insertar_asignacion")]
        public string p_insertar_asignacion {
            get {
                return ((string)(this["p_insertar_asignacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_update_asignacion")]
        public string p_update_asignacion {
            get {
                return ((string)(this["p_update_asignacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p_remove_asignacion")]
        public string p_remove_asignacion {
            get {
                return ((string)(this["p_remove_asignacion"]));
            }
        }
    }
}
